#:kivy 1.1.1
#: import utils kivy.utils
<HomeScreenExp>:
    MDBoxLayout:
        orientation: 'vertical'
        
        MDTopAppBar:
            title: "Experimental Page"
            pos_hint: {"top": 1, "right": 1}
            right_action_items:
                [["arrow-right", lambda x: app.change_screen("controller_screen"), "Switch to Controller"]]
        
        MDBoxLayout:
            orientation: 'vertical'
            padding: '20dp'